export const ADD_SEQUENCE = 'ADD_SEQUENCE';
export const REMOVE_SEQUENCE = 'REMOVE_SEQUENCE';
export const CHANGE_BPM = 'CHANGE_BPM';
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING';

export const CHANGE_TONE = 'CHANGE_TONE';
export const CHANGE_SOUND_DEF = 'CHANGE_SOUND_DEF';
export const CHANGE_EVENTS = 'CHANGE_EVENTS';
export const CHANGE_SUBDIVISION = 'CHANGE_SUBDIVISION';
